const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {_electron}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {openFixture}=require('./smoke-fixture.cjs');
(async()=>{
 const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');await fs.mkdir(out,{recursive:true});
 const env={...process.env,CIRCUIT_LAB_SMOKE:'1',CIRCUIT_LAB_TEST_PROFILE:path.join(out,'boards-profile-'+Date.now())};delete env.ELECTRON_RUN_AS_NODE;
 const app=await _electron.launch({executablePath:process.env.LAB_EXE||path.join(root,'node_modules/electron/dist/electron.exe'),args:process.env.LAB_EXE?[]:[root],cwd:root,env});
 try{
  const {blankProject,projectForBoard,validateProject}=await import('../src/project.js'),{endpointInfo,breadboardPrefix,boardPin}=await import('../src/pins.js');
  const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('#board-open');await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].showInactive());
  const saved=async()=>{await page.waitForTimeout(260);return page.evaluate(()=>JSON.parse(localStorage.getItem('stm32lab.project.v2')));};
  const point=async(x,y)=>page.evaluate(({x,y})=>{const s=document.getElementById('circuit'),q=s.createSVGPoint();q.x=x;q.y=y;const r=q.matrixTransform(s.getScreenCTM());return {x:r.x,y:r.y};},{x,y});
  const click=async(x,y)=>{const q=await point(x,y);await page.mouse.click(q.x,q.y);};
  const selectBoard=async()=>{await page.click('#board-open');await page.click('[data-board-id="nucleo-f446re"]');};
  assert.doesNotMatch(await page.locator('svg .board').textContent(),/F446RE|STM32|NUCLEO|MB1136/i);assert.match(await page.locator('svg .board').textContent(),/USER · PC13/);assert.match(await page.locator('svg .board').textContent(),/LD2 · PA5/);assert.equal(await page.locator('[data-endpoint^="board:"]').count(),108);
  // The only selectable board remains discoverable by board and MCU names.
  await page.click('#board-open');assert.equal(await page.locator('[data-board-id]').count(),1);
  for(const query of ['nucleo',' stm32 f446re ','F4','']){await page.fill('#board-search',query);assert.equal(await page.locator('[data-board-id]').count(),1);}
  await page.fill('#board-search','unknown board');assert.equal(await page.locator('[data-board-id]').count(),0);assert.match(await page.locator('#board-results').textContent(),/검색 결과가 없습니다/);await page.fill('#board-search','');await page.screenshot({path:path.join(out,'board-picker.png')});await page.click('[data-board-id]');assert.equal(await page.locator('#board-change-dialog').isVisible(),false);assert.deepEqual(await saved(),projectForBoard());
  // F5 works while typing, never reloads, and ignores held-key repeat and open dialogs.
  await page.fill('#code',(await page.locator('#code').inputValue())+'\n// shortcut marker');await page.keyboard.press('F5');assert.equal(await page.locator('#run-status').textContent(),'실행 중');assert.match(await page.locator('#code').inputValue(),/shortcut marker/);assert.equal(await page.locator('#board-open').isDisabled(),true);
  await page.evaluate(()=>window.dispatchEvent(new KeyboardEvent('keydown',{key:'F5',repeat:true,bubbles:true})));assert.equal(await page.locator('#run-status').textContent(),'실행 중');await page.keyboard.press('F5');assert.equal(await page.locator('#run-status').textContent(),'준비됨');
  let before=await saved();await selectBoard();assert.equal(await page.locator('#board-change-dialog').isVisible(),true);await page.keyboard.press('F5');assert.equal(await page.locator('#run-status').textContent(),'준비됨');await page.click('#board-change-cancel');assert.deepEqual(await saved(),before);
  // A real file save does not bypass protection against resetting changed content.
  const savePath=path.join(out,'board-work.stm32lab');await app.evaluate(({dialog},savePath)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:savePath});},savePath);await page.click('#save');await fs.access(savePath);
  await selectBoard();assert.equal(await page.locator('#board-change-dialog').isVisible(),true);await page.screenshot({path:path.join(out,'board-change-warning.png')});await page.keyboard.press('Escape');assert.deepEqual(await saved(),before);await selectBoard();await page.click('#board-change-confirm');assert.deepEqual(await saved(),projectForBoard());
  // Undo all edits back to the actual defaults: no warning is needed.
  await page.fill('#project-name','temporary');await page.locator('#project-name').press('Tab');await page.click('#undo');await selectBoard();assert.equal(await page.locator('#board-change-dialog').isVisible(),false);
  // Wires win clicks on overlapping holes in select mode. Wire mode still reaches the hole.
  const wired=blankProject();wired.wires=[{id:'overlap',from:'bb:a:8',to:'bb:e:8',color:'#dd654c'}];await openFixture(page,wired);const h=endpointInfo('bb:c:8');await click(h.x,h.y);assert.equal(await page.locator('.wire-selected').getAttribute('data-wire'),'overlap');assert.equal(await page.locator('#inspector h2').textContent(),'점퍼선');
  await page.click('#tool-wire');await click(h.x,h.y);const destination=endpointInfo('bb:f:12');await click(destination.x,destination.y);assert.equal((await saved()).wires.length,2);await page.click('#undo');assert.equal((await saved()).wires.length,1);
  // Additional boards are real searchable parts, with independent contacts and persistence.
  await openFixture(page,blankProject());await page.fill('#part-search','빵판');assert.equal(await page.locator('#part-list [data-add]:visible').count(),1);await page.click('[data-add="breadboard"]');let p=await saved(),bb=p.components.find(c=>c.type==='breadboard');assert.ok(bb);assert.equal(await page.locator('.hole').count(),800);const prefix=breadboardPrefix(bb.id);
  await page.fill('#part-search','');await page.click('#tool-wire');await page.locator(`[data-endpoint="${boardPin('3V3')}"]`).click();await page.locator(`[data-endpoint="${prefix}bb:a:8"]`).click();
  await page.click('[data-add="resistor"]');await page.locator(`[data-endpoint="${prefix}bb:e:8"]`).click();await page.locator(`[data-endpoint="${prefix}bb:f:8"]`).click();
  await page.click('#tool-wire');await page.locator(`[data-endpoint="${prefix}bb:j:8"]`).click();await page.locator(`[data-endpoint="${boardPin('GND')}"]`).click();await page.click('#tool-select');p=await saved();const resistor=p.components.find(c=>c.type==='resistor');assert.ok(resistor.attachA.startsWith(prefix));
  await page.locator('#code').focus();await page.keyboard.press('F5');await page.waitForTimeout(100);assert.equal(await page.locator('#run-status').textContent(),'실행 중');assert.ok(Number.parseFloat(await page.locator('#sim-current').textContent())>9.9);await page.keyboard.press('F5');
  await page.screenshot({path:path.join(out,'breadboard-circuit.png')});
  // Drag the board body, keeping mounted components and connected wires aligned.
  const start=await point(bb.x,bb.y-245),finish=await point(bb.x+80,bb.y+120-245);await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(finish.x,finish.y,{steps:6});await page.mouse.up();p=await saved();const moved=p.components.find(c=>c.id===bb.id),movedPart=p.components.find(c=>c.id===resistor.id);assert.ok(moved.x>bb.x+70);assert.ok(moved.y>bb.y+100);assert.ok(movedPart.x>resistor.x+70);assert.equal(p.wires.length,2);
  await page.click('#rotate');p=await saved();assert.equal(p.components.find(c=>c.id===bb.id).rotation,45);assert.equal(p.components.find(c=>c.id===resistor.id).rotation,45);assert.deepEqual(validateProject(p),p);
  await page.click('#save');const onDisk=JSON.parse(await fs.readFile(savePath,'utf8'));assert.deepEqual(onDisk,p);await page.reload();await page.waitForSelector('#code');assert.equal(await page.locator('.hole').count(),800);assert.deepEqual(await saved(),p);
  // Removing an added board removes its wires, detaches its parts, and Undo restores everything.
  const movedBoard=p.components.find(c=>c.type==='breadboard');await click(movedBoard.x,movedBoard.y);await page.click('#remove-part');let removed=await saved();assert.equal(removed.components.length,1);assert.equal(removed.components[0].type,'resistor');assert.equal(removed.wires.length,0);assert.equal(removed.components[0].attachA,undefined);assert.equal(await page.locator('.hole').count(),400);await page.click('#undo');assert.deepEqual(await saved(),p);
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1120,760));await page.screenshot({path:path.join(out,'warm-topbar-compact.png')});const overflow=await page.evaluate(()=>document.querySelector('.top-actions').getBoundingClientRect().right>innerWidth);assert.equal(overflow,false);
  assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'boards-smoke.json'),JSON.stringify({passed:true,checks:['wire hit priority over holes','wire tool can access occupied crossings','F5 in editor without reload','repeat and modal shortcut guards','warm compact header','board illustration labels removed and pins retained','single-board search','blank board selection without warning','changed saved and unsaved board reset protection','cancel and Escape preserve project','undo-to-default avoids warning','searchable additional breadboard','800 real holes and isolated topology','resistor circuit mounted on added board','board movement and rotation carry parts and wires','save/reload additional boards','board removal unplugs contacts and Undo restores'],errors},null,2));console.log('Boards UI passed: wire priority, shortcut, board picker/protection, real breadboards and persistence.');
 }finally{await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
